// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShopApp.Models
{
    public partial class MovieProduct
    {
        public int MovieId { get; set; }
        public string Title { get; set; }
        public DateTime? ReleaseDate { get; set; }
        public decimal? Price { get; set; }
        public string MediaType { get; set; }
        public string ImageUrl { get; set; }
    }
}